# Generated by Django 5.2.5 on 2025-10-11 06:39

import api.backend
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', api.backend.CustomUserManager()),
            ],
        ),
    ]
