# Generated by Django 5.2.5 on 2025-09-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopAPI', '0003_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_url',
        ),
    ]
