# Generated by Django 5.2.5 on 2025-09-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAPI', '0004_rename_image_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Groceries', 'Groceries'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Furniture', 'Furniture'), ('Toys', 'Toys'), ('Sports', 'Sports'), ('Beauty', 'Beauty'), ('Automotive', 'Automotive'), ('Health', 'Health'), ('Other', 'Other'), ('Accessories', 'Accessories')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
